---
baseUrl: example.com
languageCode: en-us
theme: hugo-personal-theme
title: Dan's Site
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
relativeURLs: true
languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-US
    weight: 0
    menu:
      main:
        - url: "/"
          name: pageAboutTranslation
          weight: 1
        - indentifier: portfolio
          url: portfolio-en/
          name: pagePortfolioTranslation
          weight: 3
      more:
        - url: "/blog"
          name: pageBlogTranslation
          weight: 2
        - url: "/resume"
          name: pageResumeTranslation
          weight: 4
      contact:
        - url: "/contact/"
          name: pageContactTranslation
          weight: 5
    permalinks:
      portfolio: /portfolio-en/:slug
  ro:
    contentDir: content/ro
    languageName: Română
    languageCode: ro-RO
    weight: 1
    menu:
      main:
        - url: "/"
          name: pageAboutTranslation
          weight: 1
        - url: "/portfolio"
          name: pagePortfolioTranslation
          weight: 3
      more:
        - url: "/blog"
          name: pageBlogTranslation
          weight: 2
        - url: "/resume"
          name: pageResumeTranslation
          weight: 4
      contact:
        - url: "/contact"
          name: pageContactTranslation
          weight: 5
  es:
    contentDir: content/es
    languageName: Español
    languageCode: es-ES
    weight: 2
    menu:
      main:
        - url: "/"
          name: pageAboutTranslation
          weight: 1
        - url: "/portofolio"
          name: pagePortfolioTranslation
          weight: 3
      more:
        - url: "/blog"
          name: pageBlogTranslation
          weight: 2
        - url: "/cv"
          name: pageResumeTranslation
          weight: 4
      contact:
        - url: "/contact"
          name: pageContactTranslation
          weight: 5

sitemap:
  changefreq: weekly
  priority: 0.5
canonifyURLs: true
uglyurls: false
params:
  useDarkMode: true
  ownerFirstName: Dan
  ownerLastName: Baghilovici
  ownerEmail:
    - contact@danbaghilovici.xyz
    - dan.baghilovici@gmail.com
  showOwnerPhone: true
  ownerPhoneNumbers:
    - "0000"
  ownerLocation: Romania
  ownerWebsite: www.danbaghilovici.xyz
  ownerSocialLinks:
    - tooltip: socialLinkTwitterTooltipTranslation
      path: <path d="M11.92,24.94A12.76,12.76,0,0,0,24.76,12.1c0-.2,0-.39,0-.59A9.4,9.4,0,0,0,27,9.18a9.31,9.31,0,0,1-2.59.71,4.56,4.56,0,0,0,2-2.5,8.89,8.89,0,0,1-2.86,1.1,4.52,4.52,0,0,0-7.7,4.11,12.79,12.79,0,0,1-9.3-4.71,4.51,4.51,0,0,0,1.4,6,4.47,4.47,0,0,1-2-.56v.05A4.53,4.53,0,0,0,9.5,17.83a4.53,4.53,0,0,1-2,.08A4.51,4.51,0,0,0,11.68,21,9.05,9.05,0,0,1,6.07,23,9.77,9.77,0,0,1,5,22.91a12.77,12.77,0,0,0,6.92,2" transform="translate(0)"/>
      link: https://twitter.com/dntzbgh
    - tooltip: socialLinkLinkedinTooltipTranslation
      path: <path d="M26.2,4H5.8C4.8,4,4,4.8,4,5.7v20.5c0,0.9,0.8,1.7,1.8,1.7h20.4c1,0,1.8-0.8,1.8-1.7V5.7C28,4.8,27.2,4,26.2,4z M11.1,24.4H7.6V13h3.5V24.4z M9.4,11.4c-1.1,0-2.1-0.9-2.1-2.1c0-1.2,0.9-2.1,2.1-2.1c1.1,0,2.1,0.9,2.1,2.1S10.5,11.4,9.4,11.4z M24.5,24.3H21v-5.6c0-1.3,0-3.1-1.9-3.1c-1.9,0-2.1,1.5-2.1,2.9v5.7h-3.5V13h3.3v1.5h0.1c0.5-0.9,1.7-1.9,3.4-1.9c3.6,0,4.3,2.4,4.3,5.5V24.3z"/>
      link: https://linkedin.com/in/dan-baghilovici-a137251b8
    - tooltip: socialLinkGithubTooltipTranslation
      path: <path d="M16,2a14,14,0,0,0-4.43,27.28c.7.13,1-.3,1-.67s0-1.21,0-2.38c-3.89.84-4.71-1.88-4.71-1.88A3.71,3.71,0,0,0,6.24,22.3c-1.27-.86.1-.85.1-.85A2.94,2.94,0,0,1,8.48,22.9a3,3,0,0,0,4.08,1.16,2.93,2.93,0,0,1,.88-1.87c-3.1-.36-6.37-1.56-6.37-6.92a5.4,5.4,0,0,1,1.44-3.76,5,5,0,0,1,.14-3.7s1.17-.38,3.85,1.43a13.3,13.3,0,0,1,7,0c2.67-1.81,3.84-1.43,3.84-1.43a5,5,0,0,1,.14,3.7,5.4,5.4,0,0,1,1.44,3.76c0,5.38-3.27,6.56-6.39,6.91a3.33,3.33,0,0,1,.95,2.59c0,1.87,0,3.38,0,3.84s.25.81,1,.67A14,14,0,0,0,16,2Z" />
      link: https://github.com/dntzbgh
  ownerSkillsSet:
    - title: Javascript
      description: ownerSkillsJavascript
      iconClass: /imgs/brands/js.svg
      weight: 1
      libs:
        - title: Typescript
          description: aa
          iconClass: /imgs/brands/typescript.svg
          weight: 2
        - title: Angular
          description: ownerSkillsAngular
          iconClass: /imgs/brands/angular.svg
          weight: 2.1
        - title: Ionic
          description: ownerSkillIonic
          iconClass: /imgs/brands/ionic.svg
          weight: 2.3
        - title: Node.js
          description: ownerSkillNode
          iconClass: /imgs/brands/nodejs.svg
          weight: 1
        - title: Express.js
          description: ownerSkillNode
          iconClass: /imgs/brands/expressjs.svg
          weight: 1.1
        - title: NestJS
          description: ownerSkillIonic
          iconClass: /imgs/brands/nestjs.svg
          weight: 1.2

    - title: Python
      description: ownerSkillsPython
      iconClass: /imgs/brands/python.svg
      weight: 2
      libs:
        - title: Django
          description: ownerSkillsDjango
          iconClass: /imgs/brands/django.svg
          weight: 1
        - title: Flask
          description: ownerSkillsDjango
          iconClass: /imgs/brands/flask.svg
          weight: 1
        - title: Numpy
          description: ownerSkillsDjango
          iconClass: /imgs/brands/numpy.svg
          weight: 1
    - title: Databases
      description: ownerSkillsPython
      iconClass: /imgs/brands/database.svg
      weight: 3
      libs:
        - title: MongoDB
          description: ownerSkillsDjango
          iconClass: /imgs/brands/mongodb.svg
          weight: 1
        - title: MySQL
          description: ownerSkillsDjango
          iconClass: /imgs/brands/postqresql.svg
          weight: 1
        - title: Firebase
          description: ownerSkillsDjango
          iconClass: /imgs/brands/firebase.svg
          weight: 1
    - title: Markup
      description: ownerSkillsPython
      iconClass: /imgs/brands/document.svg
      weight: 4
      libs:
        - title: HTML
          description: ownerSkillsDjango
          iconClass: /imgs/brands/html.svg
          weight: 1
        - title: Markdown
          description: ownerSkillsDjango
          iconClass: /imgs/brands/markdown.svg
          weight: 1
        - title: CSS
          description: ownerSkillsDjango
          iconClass: /imgs/brands/css3.svg
          weight: 1
        - title: Sass
          description: ownerSkillsDjango
          iconClass: /imgs/brands/sass.svg
          weight: 1
        - title: Bootstrap
          description: ownerSkillsDjango
          iconClass: /imgs/brands/bootstrap.svg
          weight: 1
    - title: Others
      description: ownerSkillsPython
      iconClass: /imgs/brands/random.svg
      weight: 5
      libs:
        - title: Git
          description: ownerSkillsDjango
          iconClass: /imgs/brands/git.svg
          weight: 1
        - title: Selenium
          description: ownerSkillsDjango
          iconClass: /imgs/brands/selenium.svg
          weight: 1
  ownerWorkExperience:
    - jobTitle: resumeJobTitleVlinde
      company:
        name: Vlinde Transylvania
        website: https://www.vlinde.com/
        icon: ''
      period:
        from: '2019'
        to: jobPeriodPresentTextTranslation
      description: resumeJobDescriptionVlinde
      list:
        - resumeJobBulletVlinde1
        - resumeJobBulletVlinde2
  ownerProjects:
    - name: Mauris
      motto: resumeProjectMotto0
      description: resumeProject0Description
      link: ''
      open: true
  ownerEducation:
    - title: resumeEducationUniTitleTranslation
      institution: Universidad JAUME I
      location: Castellón
      country: spainCountryTextTranslation
      period: 2013
    - title: resumeEducationBachTitleTranslation
      institution: IES Joan Coromines
      location: Benicarló
      country: spainCountryTextTranslation
      period: 2011 - 2013
  ownerInterests:
    - resumeInterestMathematicsTextTranslation
    - resumeInterestFinancesTextTranslation
    - resumeInterestFitnessTextTranslation
    - resumeInterest3dmodelingTextTranslation
  ownerLanguages:
    - language: resumeLangRomanianTranslation
      info: resumeLangNativeTranslation
    - language: resumeLangEnglishTranslation
      info:
    - language: resumeLangSpanishTranslation
      info:
